export const SHOW = 'SHOW'
export const HIDE = 'HIDE'
export const LOADING = 'LOADING'
export const FETCH_NOTES = 'FETCH_NOTES'
export const ADD_NOTE = 'ADD_NOTE'
export const DELETE_NOTE = 'DELETE_NOTE'
export const CHANGE_NOTE = 'CHANGE_NOTE'